import logo from './images/farmfood.jpg';

export const products = [
    {img: `${logo}`, 
     Title: "CHEDDAR – COLOURED", 
     Place: "UNITED KINGDOM",
     Brand: "JOSEPH HELER"
    },
    {img: `${logo}`, 
     Title: "CHEDDAR – MILD/WHITE", 
     Place: "UNITED KINGDOM",
     Brand: "JOSEPH HELER"
    },
    {img: require("./images/jhVintage.png"), 
     Title: "VINTAGE CHEDDAR", 
     Place: "UNITED KINGDOM",
     Brand: "JOSEPH HELER"
    },
    {img: require("./images/jhGlousc.png"), 
     Title: "DOUBLE GLOUCESTER", 
     Place: "UNITED KINGDOM",
     Brand: "JOSEPH HELER"
    },
    {img: `${logo}`, 
     Title: "MATURED CHEDDAR - RED", 
     Place: "UNITED KINGDOM",
     Brand: "JOSEPH HELER"
    },
    {img: require("./images/jhMatureWhite.png"),
     Title: "MATURED CHEDDAR - WHITE", 
     Place: "UNITED KINGDOM",
     Brand: "JOSEPH HELER"
    },
    {img: require("./images/jhRed.png"),
     Title: "RED LEICESTER", 
     Place: "UNITED KINGDOM",
     Brand: "JOSEPH HELER"
    },
    {img: `${logo}`, 
     Title: "MILD CHEDDAR", 
     Place: "UNITED KINGDOM",
     Brand: "MONTE CHRISTO"
    },
    {img: `${logo}`, 
     Title: "MILD COLOURED CHEDDAR", 
     Place: "UNITED KINGDOM",
     Brand: "MONTE CHRISTO"
    },
    {img: `${logo}`, 
    alt: "dwv", 
    Title: "VINTAGE CHEDDAR", 
    Place: "UNITED KINGDOM",
    Brand: "MONTE CHRISTO"
   },
   {img: `${logo}`, 
     Title: "DOUBLE GLOUCESTER", 
     Place: "UNITED KINGDOM",
     Brand: "MONTE CHRISTO"
    },
    {img: `${logo}`, 
     Title: "RED LEICESTER", 
     Place: "UNITED KINGDOM",
     Brand: "MONTE CHRISTO"
    },
    {img: `${logo}`, 
     Title: "CHESIRE CHEESE", 
     Place: "UNITED KINGDOM",
     Brand: "MONTE CHRISTO"
    },
    {img: require('./images/paysanBrie.png'), 
    alt: "dwv", 
    Title: "BRIE", 
    Place: "FRANCE",
    Brand: "PAYSAN BRETON"
   },
  
   {img: require("./images/paysanCamembert.png"), 
   alt: "dwv", 
   Title: "CAMEMBERT", 
   Place: "FRANCE",
   Brand: "PAYSAN BRETON"
  },
  {img: require("./images/paysanEmmental.png"),
  alt: "dwv", 
  Title: "EMMENTAL", 
  Place: "FRANCE",
  Brand: "PAYSAN BRETON"
  },
  
  {img: `${logo}`, 
  alt: "dwv", 
  Title: "EMMENTAL GRATED", 
  Place: "FRANCE",
  Brand: "PAYSAN BRETON"
  },
  {img: `${logo}`, 
  alt: "dwv", 
  Title: "SPECIAL PIZZA CHEESE", 
  Place: "FRANCE",
  Brand: "PAYSAN BRETON"
  },
  {img: require("./images/paysanGoatHerb.png"), 
  alt: "dwv", 
  Title: "GOAT CHEESE – HERBS & GARLIC", 
  Place: "FRANCE",
  Brand: "PAYSAN BRETON"
  },
  {img: require("./images/paysanGoatNat.png"), 
  alt: "dwv", 
  Title: "GOAT CHEESE – NATURAL", 
  Place: "FRANCE",
  Brand: "PAYSAN BRETON"
  },
  {img: require('./images/paysonGoatPepper.png'), 
  alt: "dwv", 
  Title: "GOAT CHEESE – PEPPER", 
  Place: "FRANCE",
  Brand: "PAYSAN BRETON"
  },
  {img: require("./images/goudaCheese.png"), 
  alt: "dwv", 
  Title: "GOUDA WEDGE", 
  Place: "NETHERLANDS",
  Brand: "DAILY DAIRY"
  },
  {img: require("./images/ddEDAM.png"), 
  alt: "dwv", 
  Title: "EDAM WEDGE", 
  Place: "NETHERLANDS",
  Brand: "DAILY DAIRY"
  },
  {img: require("./images/dailydairySmoked.png"), 
  alt: "dwv", 
  Title: "SMOKED CHEESE – NATURAL", 
  Place: "NETHERLANDS",
  Brand: "DAILY DAIRY"
  },
  {img: require("./images/ddSmokedHerbs.png"), 
  alt: "dwv", 
  Title: "SMOKED CHEESE – HERBS", 
  Place: "NETHERLANDS",
  Brand: "DAILY DAIRY"
  },
  {img: `${logo}`, 
  alt: "dwv", 
  Title: "SMOKED CHEESE - CHILLIES", 
  Place: "NETHERLANDS",
  Brand: "DAILY DAIRY"
  },
  {img: `${logo}`, 
  alt: "dwv", 
  Title: "SMOKED CHEESE – PEPPER", 
  Place: "NETHERLANDS",
  Brand: "DAILY DAIRY"
  },
  {img: `${logo}`, 
  alt: "dwv", 
  Title: "MOZZARELLA SLICES", 
  Place: "NETHERLANDS",
  Brand: "DAILY DAIRY"
  },
  {img: `${logo}`, 
  alt: "dwv", 
  Title: "EMMENTAL SLICES", 
  Place: "NETHERLANDS",
  Brand: "DAILY DAIRY"
  },
  {img: require("./images/DANEBLUE.png"), 
  alt: "dwv", 
  Title: "BLUE CHEESE", 
  Place: "DENMARK",
  Brand: "CANZONA"
  },
  {img: `${logo}`, 
  alt: "dwv", 
  Title: "FETA – SALAD CHEESE", 
  Place: "DENMARK",
  Brand: "TAVERNA"
  },
  {img: `${logo}`, 
  alt: "dwv", 
  Title: "SALAD CHEESE IN HERB OIL", 
  Place: "DENMARK",
  Brand: "TAVERNA"
  },
  {img: `${logo}`, 
  alt: "dwv", 
  Title: "SALAD CHEESE WITH OLIVES", 
  Place: "DENMARK",
  Brand: "TAVERNA"
  },
  {img: `${logo}`, 
  alt: "dwv", 
  Title: "SALAD CHEESE IN CHILI OIL", 
  Place: "DENMARK",
  Brand: "TAVERNA"
  },
  {img: `${logo}`, 
  alt: "dwv", 
  Title: "GRAN FORMAGGIO", 
  Place: "ITLAY",
  Brand: "COLLA S.P.A."
  },
  {img: require("./images/akadiaDanish.png"), 
  alt: "dwv", 
  Title: "FETA", 
  Place: "DENMARK",
  Brand: "AKADIA"
  },
  {img: `${logo}`, 
  alt: "dwv", 
  Title: "DANISH BRIE", 
  Place: "DENMARK",
  Brand: "DAIRY LAND"
  },
  {img: `${logo}`, 
  alt: "dwv", 
  Title: "DANISH CAMEMBERT", 
  Place: "DENMARK",
  Brand: "DAIRY LAND"
  },
  
  {img: require("./images/jhMildCol.png"), 
  alt: "dwv", 
  Title: "MILD CHEDDAR - COLOURED", 
  Place: "UNITED KINGDOM",
  Brand: "JOSEPH HELER"
  },
  {img: require("./images/jhMildWhite.png"), 
  alt: "dwv", 
  Title: "MILD CHEDDAR - WHITE", 
  Place: "UNITED KINGDOM",
  Brand: "JOSEPH HELER"
  },
  {img: `${logo}`, 
  alt: "dwv", 
  Title: "MONTREY JACK", 
  Place: "UNITED KINGDOM",
  Brand: "JOSEPH HELER"
  },
  {img: require("./images/jhMature.png"), 
  alt: "dwv", 
  Title: "MATURED CHEDDAR", 
  Place: "UNITED KINGDOM",
  Brand: "JOSEPH HELER"
  },
  {img: `${logo}`, 
  alt: "dwv", 
  Title: "PARMESAN", 
  Place: "ITALY",
  Brand: "COLA"
  },
  {img: require("./images/ddEDAM.png"), 
  alt: "dwv", 
  Title: "EDAM BALL", 
  Place: "NETHERLANDS",
  Brand: "DAIRY LAND"
  },
  
  {img: require("./images/goudaCheese.png"), 
  alt: "dwv", 
  Title: "GOUDA WHEEL", 
  Place: "NETHERLANDS",
  Brand: "DAIRY LAND"
  },
  {img: `${logo}`, 
  alt: "dwv", 
  Title: "SMOKED CHEESE NATURAL LOG", 
  Place: "NETHERLANDS",
  Brand: "DAIRY LAND"
  },
  {img: `${logo}`, 
  alt: "dwv", 
  Title: "SMOKED CHEESE HERBS LOG", 
  Place: "NETHERLANDS",
  Brand: "DAIRY LAND"
  },
  {img: require("./images/ddChilli.png"),  
  alt: "dwv", 
  Title: "SMOKED CHEESE CHILLIES LOG", 
  Place: "NETHERLANDS",
  Brand: "DAIRY LAND"
  },
  {img: require("./images/ddSmoked.png"), 
  alt: "dwv", 
  Title: "SMOKED CHEESE BLACK PEPPER",
  Place: "NETHERLANDS",
  Brand: "DAIRY LAND"
  },
  {img: `${logo}`, 
  alt: "dwv", 
  Title: "AMANTI – RED PESTO",
  Brand: "DAIRY LAND",
  Place: "NETHERLANDS"
  },
  {img: `${logo}`, 
  alt: "dwv", 
  Title: "AMANTI – GREEN PESTO",
  Brand: "DAIRY LAND",
  Place: "NETHERLANDS"
  },
  {img: `${logo}`, 
  alt: "dwv", 
  Title: "AMANTI TRUFFLE",
  Brand: "DAIRY LAND",
  Place: "NETHERLANDS"
  },
  {img: `${logo}`, 
  alt: "dwv", 
  Title: "AMANTI MUSTARD",
  Brand: "DAIRY LAND",
  Place: "NETHERLANDS"
  },
  {img: `${logo}`, 
  alt: "dwv", 
  Title: "AMANTI CUMIN",
  Brand: "DAIRY LAND",
  Place: "NETHERLANDS"
  },
  {img: `${logo}`, 
  alt: "dwv", 
  Title: "AMANTI CHILLI",
  Brand: "DAIRY LAND",
  Place: "NETHERLANDS"
  },
  {img: `${logo}`, 
  alt: "dwv", 
  Title: "AMANTI BLACK PEPPER",
  Brand: "DAIRY LAND",
  Place: "NETHERLANDS"
  },
  {img: `${logo}`, 
  alt: "dwv", 
  Title: "GOAT CHEESE",
  Brand: "QUESOS EL PASTOR",
  Place: "SPAIN"
  },
  {img: `${logo}`, 
  alt: "dwv", 
  Title: "GOAT CHEESE",
  Brand: "PAYSAN BRETON",
  Place: "FRANCE"
  },
  {img: `${logo}`, 
  alt: "dwv", 
  Title: "GOAT CHEESE",
  Brand: "PAYSAN BRETON",
  Place: "FRANCE"
  },
  {img: `${logo}`, 
  alt: "dwv", 
  Title: "FRENCH EMMENTEL",
  Brand: "PAYSAN BRETON",
  Place: "FRANCE"
  },
  
  {img: require("./images/canzonaBlue.png"), 
  alt: "dwv", 
  Title: "BLUE CHEESE",
  Brand: "CANZONA",
  Place: "DENMARK"
  },
  {img: require(`./images/TAVERNAGREEKFETA.png`), 
  alt: "dwv", 
  Title: "GREEK FETA",
  Brand: "TAVERNA",
  Place: "GREECE"
  },
  {img: require('./images/paysanBrie.png'), 
  alt: "dwv", 
  Title: "FRESH BRIE",
  Brand: "PAYSAN BRETON",
  Place: "FRANCE"
  },
  {img: `${logo}`, 
  alt: "dwv", 
  Title: "STILTON",
  Brand: "BISHOP CROPWELL",
  Place: "UNITED KINGDOM"
  },
  {img: `${logo}`, 
  alt: "dwv", 
  Title: "PECORINO",
  Brand: "COLLA SPA",
  Place: "ITALY"
  },
  {img: `${logo}`, 
  alt: "dwv", 
  Title: "PROVOLONE",
  Brand: "COLLA SPA",
  Place: "ITALY"
  },
  {img: `${logo}`, 
  alt: "dwv", 
  Title: "RACLETTE",
  Brand: "PAYSAN BRETON",
  Place: "FRANCE"
  },
  {img: require('./images/paysanWhipping.png'),
    alt: "dwv", 
     Title: "UHT WHIPPING CREAM", 
     Brand: "PAYSAN BRETON",
     Place: "FRANCE",
     Qt: "1L"
    },
    {img: require('./images/paysanCooking.png'), 
    alt: "dwv", 
     Title: "UHT COOKING CREAM", 
     Brand: "PAYSAN BRETON",
     Place: "FRANCE",
     Qt: "1L"
    },
    {img: require('./images/paysanWhipping.png'),
    alt: "dwv", 
     Title: "UHT WHIPPING CREAM", 
     Brand: "PAYSAN BRETON",
     Place: "FRANCE",
     Qt: "200 ML"
    },
    {img: require('./images/paysanCooking.png'), 
    alt: "dwv", 
     Title: "UHT COOKING CREAM", 
     Brand: "PAYSAN BRETON",
     Place: "FRANCE",
     Qt: "200 ML"
    },
    {img: `${logo}`, 
    alt: "dwv", 
     Title: "TABLE BUTTER SALTED", 
     Brand: "PAYSAN BRETON",
     Place: "FRANCE",
     Qt: "200 GM"
    },
    {img: `${logo}`, 
    alt: "dwv", 
     Title: "TABLE BUTTER UNSALTED", 
     Brand: "PAYSAN BRETON",
     Place: "FRANCE",
     Qt: "200 GM"
    },
    {img: `${logo}`, 
    alt: "dwv", 
     Title: "BUTTER SHEET", 
     Brand: "PAYSAN BRETON",
     Place: "FRANCE",
     Qt: "2 KG"
    },
    {img: `${logo}`, 
    alt: "dwv", 
     Title: "BUTTER CHIPLETS SALTED(with sea salt)", 
     Brand: "PAYSAN BRETON",
     Place: "FRANCE",
     Qt: "10 GM"
    },
    {img: `${logo}`, 
    alt: "dwv", 
     Title: "BUTTER CHIPLETS SLIGHTLY SALTED", 
     Brand: "PAYSAN BRETON",
     Place: "FRANCE",
     Qt: "10 GM"
    },
    {img: `${logo}`, 
    alt: "dwv", 
     Title: "BUTTER CHIPLETS UNSALTED", 
     Brand: "PAYSAN BRETON",
     Place: "FRANCE",
     Qt: "10 MG"
    },
    {img: `${logo}`, 
    alt: "dwv", 
     Title: "BUTTER SALTED", 
     Brand: "PAYSAN BRETON",
     Place: "FRANCE",
     Qt: "500 GM"
    },
    {img: `${logo}`, 
    alt: "dwv", 
     Title: "BUTTER UNSALTED", 
     Brand: "PAYSAN BRETON",
     Place: "FRANCE",
     Qt: "500 GM"
    },
    {img: require("./images/gnoschSaffron.png"), 
    alt: "dwv", 
     Title: "SAFFRON", 
     Brand: "GNOSCH",
     Place: "IRAN",
     Qt: "1 GM"
    },
  ]